### ISSUE TITLE
Range-Filter with Jersey 1.19

### ISSUE THREAD

**Issue by rokaa** [heruan/jaxrs-range-filter#2]
Hei heruan,
   i was wondering whether it is possible with Jersey 1.19. Here is what i did: 

`public class RangeResponseFilter implements ContainerResponseFilter {

    private static final String ACCEPT_RANGES = "Accept-Ranges";

    private static final String BYTES_RANGE = "bytes";

    private static final String RANGE = "Range";

    private static final String IF_RANGE = "If-Range";

    private void applyFilter(ContainerRequest requestContext, ContainerResponse responseContext)
        throws IOException {
        
        String rangeHeader = requestContext.getHeaderValue(RANGE);
       
        String contentType = responseContext.getMediaType().toString();
       
        responseContext.getEntityType();
        
        OutputStream originOutputStream = responseContext.getOutputStream();
        RangedOutputStream rangedOutputStream = new RangedOutputStream(originOutputStream, rangeHeader, contentType,
            responseContext.getHttpHeaders());
        
        //206 status code
        responseContext.setStatus(206);
        //responseContext.setStatus(Status.);
        
        //responseContext.set
        responseContext.setEntity(rangedOutputStream);

    }

    @Override
    public ContainerResponse filter(ContainerRequest requestContext, ContainerResponse responseContext){
        responseContext.getHttpHeaders().add(ACCEPT_RANGES, BYTES_RANGE);
        //responseContext.
        if (requestContext.getRequestHeaders().containsKey(RANGE)) {
            if (requestContext.getRequestHeaders().containsKey(IF_RANGE)) {
                String ifRangeHeader = requestContext.getHeaderValue(IF_RANGE);
                if (responseContext.getHttpHeaders().containsKey(HttpHeaders.ETAG)) {
                    if (responseContext.getHeaderValue(HttpHeaders.ETAG).equals(ifRangeHeader)) {
                        try {
                            this.applyFilter(requestContext, responseContext);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        return responseContext;
                    }
                }
                if (responseContext.getHttpHeaders().containsKey(HttpHeaders.LAST_MODIFIED)) {
                    if (responseContext.getHeaderValue(HttpHeaders.LAST_MODIFIED).equals(ifRangeHeader)) {
                        try {
                            this.applyFilter(requestContext, responseContext);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        return responseContext;
                    }
                }
            } else {
                try {
                    
                    this.applyFilter(requestContext, responseContext);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return responseContext;
    }
`

I left the RangedOutputStream the same, it was not complaining. 

But i query string with range i get this error: 
javax.ws.rs.WebApplicationException: com.sun.jersey.api.MessageException: A message body writer for Java class org.jivesoftware.openfire.plugin.rest.service.RangedOutputStream, and Java type class org.jivesoftware.openfire.plugin.rest.service.RangedOutputStream, and MIME media type text/plain was not found.

I have all dependencies: i've got jersey-bundle-1.19.3.jar. 

Any help?

**Comment by heruan** [comment]
I've just released [1.0.0](https://github.com/heruan/jaxrs-range-filter/releases/tag/1.0.0) which is now on Maven and totally JAX-RS implementation agnostic. Could you please give it a try and see if the issue is solved?

**Comment by rokaa** [comment]
I am trying to do it(using Example Usage), but getting this error:

```
com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
	com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99)
	com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1298)
	com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:169)
	com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:775)
	com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:771)
	com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
	com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771)
	com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766)
	com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488)
	com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318)
	com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609)
	com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210)
	com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373)
	com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
```

I believe we must register the resource somehow? Tried providing package in web.xml, doesn't work

**Comment by rokaa** [comment]
Hei Heruan,
    I did add the resources, but then i am getting this error: 
```
java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:120)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:662)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)

```
And i think it is related to 
```
<dependency>
            <groupId>javax.ws.rs</groupId>
            <artifactId>javax.ws.rs-api</artifactId>
            <version>${jaxrs.version}</version>
</dependency>
```
You are using 2.1 version of rs-api, and it requires version of 2 or higher for jax-rs or jersey, 
this link might be helpful (https://stackoverflow.com/questions/30176811/abstractmethoderror-using-uribuilder-on-jax-rs)

**Comment by heruan** [comment]
Then I think you should consider it requiring JAX-RS >= 2.1. Is there any special reason you cannot upgrade?

**Comment by rokaa** [comment]
Yeah, i can not update it due to legacy code. Is 2.0 backwards compatible? I think no for sure right...even the naming is different. 

Did you see my first comment? i tried to change your code for Jax-rs 1.19, but got error. 
Also this is the link with Jax-Rs 1.19 i have created repo. Can you maybe take a look? (https://github.com/rokaa/jaxrs-byte-range) Just have to clone the project and run on tomcat

**Comment by heruan** [comment]
You do `responseContext.setEntity(rangedOutputStream)` in your `applyFilter` method, that's the problem. You have to use `setEntityStream` if available in your JAX-RS version; otherwise, I'm afraid you can't.

**Comment by rokaa** [comment]
Yeah i know that, don't have `setEntityStream`. There is one with `setEntity(Object obj, Type type)` though, but not sure what to pass there. 
Anyways thank you very much. 
Do you want me to close the issue? or should i leave it open?

**Comment by heruan** [comment]
One strategy could be to implement a `MessageBodyWriter` and write to the output stream the ranged response there (with the same logic as this one).

**Comment by rokaa** [comment]
Can you make it, maybe a draft? (i am not quite following you)

**Comment by heruan** [comment]
I mean:

```java
class RangedBodyWriter implements MessageBodyWriter<Object> {

    // ...

    @Override
    public void writeTo(Object entity, Class<?> type, Type genericType, Annotation[] annotations,
                        MediaType mediaType, MultivaluedMap<String, Object> httpHeaders,
                        OutputStream out) throws IOException, WebApplicationException {
        // write to `out` with the same logic as in RangedOutputStream
    }
}
```

You can make different body writers for different media types, if you need to.
